-- 026-assistant-threads.sql
-- ChatGPT-style conversational assistant — issue #135 phase 1.
--
-- Two tables, one parent / one child:
--
--   assistant_threads — one row per conversation. The user creates a thread
--     when they send their first message in a "fresh" chat; subsequent
--     messages append to the thread. `title` is auto-derived from the first
--     user message (truncated) and is editable in a future phase.
--
--   assistant_messages — append-only message log per thread. `role` is the
--     usual chat-completion role ('user' | 'assistant' | 'system'). `content`
--     is text only for phase 1; phase 2 may add structured tool-call payloads
--     (track separately so the schema doesn't have to change).
--
-- Threads are scoped per user (no sharing in phase 1 — out-of-scope per the
-- issue). Deleting a thread cascades messages.
--
-- updated_at on threads reflects the last message added; bumped in
-- application code (CRDB doesn't run PL/pgSQL triggers the same way Postgres
-- does — same pattern as oauth_tokens / connector_cursors / mempalace).

CREATE TABLE IF NOT EXISTS assistant_threads (
  id          UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id     UUID        NOT NULL,
  title       STRING      NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Hot-path index for `GET /api/assistant/threads` — most-recently-active
-- threads first, scoped to the requesting user.
CREATE INDEX IF NOT EXISTS assistant_threads_user_updated_idx
  ON assistant_threads (user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS assistant_messages (
  id          UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  thread_id   UUID        NOT NULL REFERENCES assistant_threads(id) ON DELETE CASCADE,
  role        STRING      NOT NULL,
  content     STRING      NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Optional metadata blob — for phase 2 we'll record provider/model/latency
  -- so the user can see "this reply was generated by claude-opus in 1.2s."
  -- Phase 1 leaves this empty/nullable.
  metadata    JSONB
);

-- Read-path index: messages for one thread in chronological order.
CREATE INDEX IF NOT EXISTS assistant_messages_thread_created_idx
  ON assistant_messages (thread_id, created_at ASC);
