-- 049-promotion-offers.sql
-- Worker→API bridge: durable promotion-offer surface (#310).
--
-- Background. `runPromotionEligibilityCheckJob` decides which MCP
-- servers have earned a trust-tier promotion and (until this migration)
-- emitted a `capability:promotion-offered` SSE event directly. The
-- worker has no `sseManager` instance (that lives in apps/api), so the
-- SSE emit had to be injected — and when #304 wired the job, the
-- emitter wasn't available, which made the job logging-only. The
-- ceremony existed in code but never fired for a real user.
--
-- This table is the durable surface that replaces the direct emit.
-- The worker writes a row when a server becomes eligible. The
-- dashboard polls for pending offers — this is the source of truth.
-- The API may also emit SSE on inserts as a UX optimization for live
-- dashboards, but the table is what survives restarts and what the
-- dashboard re-renders from on reload.
--
-- Idempotency. A worker tick that re-runs the eligibility check
-- shouldn't pile up duplicate offers for the same (user, server,
-- proposed_tier) tuple while a previous offer is still pending. The
-- partial unique index below enforces that — only one PENDING offer
-- per (server_id, proposed_tier). Once responded_at is set the row
-- drops out of the partial index, allowing a future re-promotion
-- attempt at the same tier (after a user-initiated demotion).
--
-- Why store `current_tier` AND `proposed_tier`. The eligibility-check
-- snapshot of the server's tier may be stale by the time the user
-- clicks Accept (admin demoted the server in between, etc.). On the
-- accept path the API compares `mcp_servers.trust_tier` against
-- `current_tier` and refuses if they no longer match — the user is
-- accepting a stale offer that doesn't reflect the current state.
--
-- `response` is text not enum so we can add values without a schema
-- migration; current vocabulary: 'accepted' | 'rejected' | 'dismissed'.
-- 'dismissed' = the user closed the modal without explicit accept/
-- reject. Same operational effect as 'rejected' for now but the
-- distinction matters for the eligibility engine's next run (a
-- dismissed offer can be re-offered later; a rejected one is a
-- stronger signal we shouldn't keep nagging).

CREATE TABLE IF NOT EXISTS promotion_offers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  server_id UUID NOT NULL REFERENCES mcp_servers(id) ON DELETE CASCADE,
  current_tier STRING NOT NULL,
  proposed_tier STRING NOT NULL,
  -- Reason copy generated by the trust-tier engine. Surfaced in the
  -- modal so the user understands WHY they're being offered a
  -- promotion ("4 consecutive approvals + 80% approval ratio").
  reason STRING NOT NULL,
  -- Decision-count snapshot at offer time, for the dashboard to
  -- show "based on X decisions, Y approvals." Cheap to recompute
  -- at accept time but storing the snapshot keeps the modal
  -- deterministic — the dashboard renders whatever the offer
  -- recorded, not "what's true at render time."
  decisions_observed_count INT NOT NULL DEFAULT 0,
  approved_count INT NOT NULL DEFAULT 0,
  offered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  responded_at TIMESTAMPTZ,
  response STRING,
  INDEX (user_id, offered_at DESC),
  INDEX (user_id, responded_at, offered_at DESC)
);

-- One pending offer per (server, proposed_tier). Once the user
-- responds, the row drops out of the partial index — the worker
-- can re-offer at the same tier in a future ceremony if eligibility
-- conditions are met again.
CREATE UNIQUE INDEX IF NOT EXISTS promotion_offers_pending_uniq
  ON promotion_offers (server_id, proposed_tier)
  WHERE responded_at IS NULL;
