import { ConfidenceLevel } from './enums.js';

/**
 * The digital twin profile: a structured model of the user's preferences,
 * decision patterns, and inferred behaviors.
 */
export interface TwinProfile {
  id: string;
  userId: string;
  version: number;
  preferences: Preference[];
  inferences: Inference[];
  createdAt: Date;
  updatedAt: Date;
}

/**
 * A single preference the twin has learned about the user.
 */
export interface Preference {
  id: string;
  domain: string;
  key: string;
  value: unknown;
  confidence: ConfidenceLevel;
  source: PreferenceSource;
  evidenceIds: string[];
  createdAt: Date;
  updatedAt: Date;
}

/**
 * How a preference was established.
 */
export type PreferenceSource = 'explicit' | 'inferred' | 'default' | 'corrected';

/**
 * An inference drawn from evidence about user behavior.
 */
export interface Inference {
  id: string;
  domain: string;
  key: string;
  value: unknown;
  confidence: ConfidenceLevel;
  supportingEvidenceIds: string[];
  contradictingEvidenceIds: string[];
  reasoning: string;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * A piece of evidence from user behavior that supports or contradicts an inference.
 */
export interface TwinEvidence {
  id: string;
  userId: string;
  source: string;
  type: string;
  data: Record<string, unknown>;
  domain: string;
  timestamp: Date;
}

/**
 * Feedback from the user about a decision SkyTwin made.
 */
export interface FeedbackEvent {
  id: string;
  userId: string;
  decisionId: string;
  feedbackType: 'approve' | 'reject' | 'correct' | 'ignore' | 'undo';
  correctedAction?: string;
  correctedValue?: unknown;
  reason?: string;
  undoReasoning?: UndoReasoning;
  timestamp: Date;
}

/**
 * Detailed reasoning captured when a user undoes an action.
 */
export interface UndoReasoning {
  whatWentWrong: string;
  whichStep?: string;
  preferredAlternative?: string;
  severity: 'minor' | 'moderate' | 'severe';
}

/**
 * A preference proposal generated by the archaeology system.
 */
export interface PreferenceProposal {
  id: string;
  userId: string;
  domain: string;
  key: string;
  value: unknown;
  confidence: ConfidenceLevel;
  supportingEvidence: Array<{ evidenceId: string; summary: string }>;
  status: 'pending' | 'accepted' | 'rejected' | 'expired';
  detectedAt: Date;
  respondedAt?: Date;
  expiresAt: Date;
}

/**
 * A stored raw signal for cross-domain correlation.
 */
export interface StoredSignal {
  id: string;
  userId: string;
  source: string;
  type: string;
  domain: string;
  data: Record<string, unknown>;
  timestamp: Date;
  retentionUntil: Date;
  createdAt: Date;
}

/**
 * A correlation between signals across domains.
 */
export interface SignalCorrelation {
  id: string;
  signalIds: string[];
  correlationType: string;
  confidence: ConfidenceLevel;
  description: string;
}

/**
 * Result of the whatWouldIDo() query.
 */
export interface WhatWouldIDoRequest {
  situation: string;
  domain?: string;
  urgency?: 'low' | 'medium' | 'high' | 'critical';
}

/**
 * Response from the whatWouldIDo() query.
 */
export interface WhatWouldIDoResponse {
  predictedAction: import('./decision.js').CandidateAction | null;
  confidence: ConfidenceLevel;
  reasoning: string;
  wouldAutoExecute: boolean;
  policyNotes?: string;
  alternativeActions: import('./decision.js').CandidateAction[];
  predictionId: string;
}

/**
 * Twin export data — complete portable snapshot.
 */
export interface TwinExport {
  userId: string;
  exportedAt: Date;
  format: 'json' | 'markdown';
  profile: TwinProfile;
  patterns: import('./patterns.js').BehavioralPattern[];
  traits: import('./patterns.js').CrossDomainTrait[];
  temporalProfile: import('./patterns.js').TemporalProfile;
}

/**
 * A briefing item in the morning briefing.
 */
export interface BriefingItem {
  actionDescription: string;
  domain: string;
  confidence: ConfidenceLevel;
  urgency: 'low' | 'medium' | 'high' | 'critical';
  reasoning: string;
  wouldAutoExecute: boolean;
  decisionId?: string;
}

/**
 * A morning briefing generated by the proactive scanner.
 */
export interface Briefing {
  id: string;
  userId: string;
  scanId?: string;
  items: BriefingItem[];
  emailSent: boolean;
  createdAt: Date;
}

/**
 * Proactive scan result.
 */
export interface ProactiveScanResult {
  scanId: string;
  userId: string;
  scanType: 'daily' | 'hourly' | 'manual';
  autoActions: import('./decision.js').DecisionOutcome[];
  approvalNeeded: import('./decision.js').DecisionOutcome[];
  briefingItems: BriefingItem[];
  startedAt: Date;
  completedAt: Date;
}

/**
 * A skill gap detected by the execution router.
 */
export interface SkillGap {
  id: string;
  actionType: string;
  actionDescription: string;
  attemptedAdapters: string[];
  userId: string;
  decisionId?: string;
  ironclawIssueUrl?: string;
  loggedAt: Date;
}

/**
 * Trust characteristics declared by an execution adapter.
 */
export interface AdapterTrustProfile {
  name: string;
  reversibilityGuarantee: 'full' | 'partial' | 'none';
  authModel: 'hmac' | 'oauth' | 'api_key' | 'none';
  auditTrail: boolean;
  riskModifier: number;
}

/**
 * The decision the execution router made about which adapter to use.
 */
export interface RoutingDecision {
  selectedAdapter: string;
  trustProfile: AdapterTrustProfile;
  riskModifierApplied: number;
  fallbackChain: string[];
  reasoning: string;
}
