import { describe, expect, it } from 'vitest';
import {
  generateKeyPair,
  generatePairingCode,
  isValidBase64Key,
  isValidPairingCode,
  openMessage,
  sealMessage,
} from '../federation/crypto.js';

describe('generateKeyPair', () => {
  it('returns a 32-byte public key and 32-byte secret key as base64', () => {
    const kp = generateKeyPair();
    expect(Buffer.from(kp.publicKeyB64, 'base64').length).toBe(32);
    expect(Buffer.from(kp.secretKeyB64, 'base64').length).toBe(32);
  });

  it('returns a fresh keypair on every call', () => {
    const a = generateKeyPair();
    const b = generateKeyPair();
    expect(a.publicKeyB64).not.toEqual(b.publicKeyB64);
    expect(a.secretKeyB64).not.toEqual(b.secretKeyB64);
  });
});

describe('generatePairingCode', () => {
  it('returns exactly 6 digits', () => {
    for (let i = 0; i < 20; i++) {
      const c = generatePairingCode();
      expect(c).toMatch(/^\d{6}$/);
    }
  });
});

describe('isValidPairingCode', () => {
  it('accepts 6-digit numeric strings', () => {
    expect(isValidPairingCode('123456')).toBe(true);
    expect(isValidPairingCode('000000')).toBe(true);
    expect(isValidPairingCode('999999')).toBe(true);
  });

  it('rejects wrong length, non-numeric, or non-string', () => {
    expect(isValidPairingCode('12345')).toBe(false);
    expect(isValidPairingCode('1234567')).toBe(false);
    expect(isValidPairingCode('12345a')).toBe(false);
    expect(isValidPairingCode(123456 as unknown as string)).toBe(false);
    expect(isValidPairingCode(null)).toBe(false);
    expect(isValidPairingCode(undefined)).toBe(false);
    expect(isValidPairingCode('')).toBe(false);
  });
});

describe('isValidBase64Key', () => {
  it('accepts a key generated by generateKeyPair', () => {
    const kp = generateKeyPair();
    expect(isValidBase64Key(kp.publicKeyB64)).toBe(true);
    expect(isValidBase64Key(kp.secretKeyB64)).toBe(true);
  });

  it('rejects non-base64 strings', () => {
    expect(isValidBase64Key('!!!notbase64!!!')).toBe(false);
    expect(isValidBase64Key('')).toBe(false);
    expect(isValidBase64Key('x')).toBe(false);
  });

  it('rejects base64 of wrong length', () => {
    expect(isValidBase64Key(Buffer.from('a'.repeat(16)).toString('base64'))).toBe(false);
    expect(isValidBase64Key(Buffer.from('a'.repeat(64)).toString('base64'))).toBe(false);
  });
});

describe('seal/open round-trip', () => {
  it('decrypts and parses payload sealed by the corresponding sender keypair', () => {
    const sender = generateKeyPair();
    const recipient = generateKeyPair();
    const payload = { hello: 'world', n: 42, list: [1, 2, 3] };

    const { nonceB64, ciphertextB64 } = sealMessage(
      payload,
      recipient.publicKeyB64,
      sender.secretKeyB64,
    );
    const opened = openMessage(
      nonceB64,
      ciphertextB64,
      sender.publicKeyB64,
      recipient.secretKeyB64,
    );
    expect(opened).toEqual(payload);
  });

  it('returns null when sealed by a different sender', () => {
    const sender = generateKeyPair();
    const wrongSender = generateKeyPair();
    const recipient = generateKeyPair();

    const { nonceB64, ciphertextB64 } = sealMessage('hi', recipient.publicKeyB64, sender.secretKeyB64);
    const opened = openMessage(
      nonceB64,
      ciphertextB64,
      wrongSender.publicKeyB64,
      recipient.secretKeyB64,
    );
    expect(opened).toBeNull();
  });

  it('returns null when ciphertext is tampered', () => {
    const sender = generateKeyPair();
    const recipient = generateKeyPair();

    const { nonceB64, ciphertextB64 } = sealMessage('hi', recipient.publicKeyB64, sender.secretKeyB64);
    const tampered = Buffer.from(ciphertextB64, 'base64');
    if (tampered.length === 0) throw new Error('unexpected empty ciphertext');
    tampered[0] = (tampered[0]! ^ 0xff) & 0xff;
    const opened = openMessage(
      nonceB64,
      tampered.toString('base64'),
      sender.publicKeyB64,
      recipient.secretKeyB64,
    );
    expect(opened).toBeNull();
  });

  it('returns null when nonce is wrong', () => {
    const sender = generateKeyPair();
    const recipient = generateKeyPair();
    const { ciphertextB64 } = sealMessage('hi', recipient.publicKeyB64, sender.secretKeyB64);
    const wrongNonce = Buffer.from('a'.repeat(24), 'utf8').toString('base64');
    const opened = openMessage(
      wrongNonce,
      ciphertextB64,
      sender.publicKeyB64,
      recipient.secretKeyB64,
    );
    expect(opened).toBeNull();
  });
});
