import React, { useState, useCallback, useRef, useEffect } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  ActivityIndicator,
  Alert,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { discoverSkyTwin, buildBaseUrl } from '../services/discovery';
import {
  classifyTimeout,
  troubleshootingMessage,
  normalizeManualAddress,
  type DiscoveryFailureCause,
} from '../services/discovery-diagnostics';
import { SkyTwinApiClient } from '../services/api-client';
import { saveSession } from '../services/session-store';
import { rememberManualHost, getRememberedManualHost } from '../services/paired-host-store';

interface PairingScreenProps {
  onPaired: () => void;
}

type PairingState =
  | { phase: 'scan' }
  | { phase: 'discovering'; token: string; userId: string; host: string | null }
  | { phase: 'found'; token: string; userId: string; baseUrl: string }
  | { phase: 'error'; message: string; cause?: DiscoveryFailureCause; token?: string; userId?: string }
  | { phase: 'manual' };

/**
 * QR code pairing screen.
 *
 * Scans a QR code generated by the desktop app, extracts the token and userId,
 * then discovers the SkyTwin API on the local network via mDNS.
 */
export function PairingScreen({ onPaired }: PairingScreenProps): React.JSX.Element {
  const [permission, requestPermission] = useCameraPermissions();
  const [state, setState] = useState<PairingState>({ phase: 'scan' });
  const [manualIp, setManualIp] = useState('');
  const [connecting, setConnecting] = useState(false);
  const scannedRef = useRef(false);
  // Credentials from the most recent QR scan, kept so the manual-IP
  // fallback can COMPLETE pairing (not just probe) when mDNS fails on a
  // multicast-blocked network (#384).
  const scannedCredsRef = useRef<{ token: string; userId: string } | null>(null);

  // Reset scan lock when returning to scan phase
  useEffect(() => {
    if (state.phase === 'scan') {
      scannedRef.current = false;
    }
  }, [state.phase]);

  // Pre-fill the manual field with the last address that worked, so a
  // returning user on the same office network doesn't re-type their IP.
  useEffect(() => {
    if (state.phase === 'manual' && manualIp.length === 0) {
      getRememberedManualHost()
        .then((host) => { if (host) setManualIp(host); })
        .catch(() => { /* best-effort pre-fill */ });
    }
  }, [state.phase, manualIp.length]);

  const parseQrUrl = useCallback(
    (url: string): { token: string; userId: string; host: string } | null => {
      try {
        const parsed = new URL(url);
        const token = parsed.searchParams.get('token');
        const userId = parsed.searchParams.get('userId');
        if (!token || !userId) return null;
        return { token, userId, host: parsed.host };
      } catch {
        return null;
      }
    },
    [],
  );

  const handleBarCodeScanned = useCallback(
    async (scanResult: { data: string }) => {
      // Prevent duplicate scans
      if (scannedRef.current) return;
      scannedRef.current = true;

      const parsed = parseQrUrl(scanResult.data);
      if (!parsed) {
        setState({
          phase: 'error',
          message: 'Invalid QR code. Make sure you scan the SkyTwin pairing code from your desktop.',
        });
        return;
      }

      // Remember the scanned creds so the manual fallback can finish
      // pairing if mDNS / the QR host both fail.
      scannedCredsRef.current = { token: parsed.token, userId: parsed.userId };

      setState({
        phase: 'discovering',
        token: parsed.token,
        userId: parsed.userId,
        host: parsed.host,
      });

      // Try mDNS discovery first.
      const discovered = await discoverSkyTwin(5000, false);
      const servicesFound = discovered !== null;
      const baseUrl = discovered
        ? buildBaseUrl(discovered)
        : `http://${parsed.host}`;

      // Verify the API is reachable.
      const client = new SkyTwinApiClient(baseUrl, parsed.token, 5000);
      const healthResult = await client.getServiceStatus();

      if (healthResult.success) {
        setState({
          phase: 'found',
          token: parsed.token,
          userId: parsed.userId,
          baseUrl,
        });
      } else {
        // Classify WHY so the error screen can point the user at the
        // right fix (manual IP for blocked multicast vs. firewall).
        const cause = classifyTimeout({
          servicesFound,
          connectAttempted: true,
          connectFailed: true,
        });
        setState({
          phase: 'error',
          message: troubleshootingMessage(cause),
          cause,
          token: parsed.token,
          userId: parsed.userId,
        });
      }
    },
    [parseQrUrl],
  );

  const handleConnect = useCallback(async () => {
    if (state.phase !== 'found') return;
    setConnecting(true);

    try {
      await saveSession(state.token, state.baseUrl, state.userId);
      onPaired();
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Failed to save session';
      Alert.alert('Connection Error', message);
    } finally {
      setConnecting(false);
    }
  }, [state, onPaired]);

  const handleManualConnect = useCallback(async () => {
    const baseUrl = normalizeManualAddress(manualIp);
    if (baseUrl === null) {
      Alert.alert(
        'Enter a valid address',
        "Enter your computer's IP address (e.g. 192.168.1.42), optionally with a port (192.168.1.42:3100).",
      );
      return;
    }

    setConnecting(true);

    const creds = scannedCredsRef.current;
    // Use the scanned token for the health probe when we have it — the
    // API's status endpoint is auth-gated, so an empty token would 401
    // even against a reachable server.
    const client = new SkyTwinApiClient(baseUrl, creds?.token ?? '', 5000);
    const healthResult = await client.getServiceStatus();

    if (!healthResult.success) {
      setConnecting(false);
      setState({
        phase: 'error',
        message: `Could not reach SkyTwin at ${baseUrl}. Check the address and make sure SkyTwin is running.`,
        cause: 'unknown',
        ...(creds ? { token: creds.token, userId: creds.userId } : {}),
      });
      return;
    }

    // Reachable. If we have scanned creds, COMPLETE pairing here and
    // remember the address for next time. If not (user came straight to
    // manual without scanning), fall back to asking them to scan.
    if (creds) {
      try {
        await saveSession(creds.token, baseUrl, creds.userId);
        await rememberManualHost(manualIp.trim()).catch(() => undefined);
        setConnecting(false);
        onPaired();
        return;
      } catch (err: unknown) {
        setConnecting(false);
        Alert.alert('Connection Error', err instanceof Error ? err.message : 'Failed to save session');
        return;
      }
    }

    setConnecting(false);
    Alert.alert(
      'SkyTwin Found',
      `Found SkyTwin at ${baseUrl}. To complete pairing, scan the QR code from your desktop app.`,
    );
    setState({ phase: 'scan' });
  }, [manualIp, onPaired]);

  const handleRetry = useCallback(() => {
    setState({ phase: 'scan' });
  }, []);

  // Camera permission not yet determined
  if (!permission) {
    return (
      <View style={styles.container}>
        <ActivityIndicator size="large" color="#4a90d9" />
      </View>
    );
  }

  // Camera permission denied
  if (!permission.granted) {
    return (
      <View style={styles.container}>
        <Text style={styles.title}>Camera Access Needed</Text>
        <Text style={styles.subtitle}>
          SkyTwin needs camera access to scan the pairing QR code from your desktop.
        </Text>
        <TouchableOpacity style={styles.primaryButton} onPress={requestPermission}>
          <Text style={styles.primaryButtonText}>Grant Camera Access</Text>
        </TouchableOpacity>
      </View>
    );
  }

  // Scanning phase
  if (state.phase === 'scan') {
    return (
      <View style={styles.container}>
        <Text style={styles.title}>Pair with Desktop</Text>
        <Text style={styles.subtitle}>
          Open SkyTwin on your computer and scan the QR code shown in Settings.
        </Text>
        <View style={styles.cameraContainer}>
          <CameraView
            style={styles.camera}
            facing="back"
            barcodeScannerSettings={{
              barcodeTypes: ['qr'],
            }}
            onBarcodeScanned={handleBarCodeScanned}
          />
          <View style={styles.scanOverlay}>
            <View style={styles.scanFrame} />
          </View>
        </View>
        <TouchableOpacity
          style={styles.secondaryButton}
          onPress={() => setState({ phase: 'manual' })}
        >
          <Text style={styles.secondaryButtonText}>Enter address manually</Text>
        </TouchableOpacity>
      </View>
    );
  }

  // Discovering phase
  if (state.phase === 'discovering') {
    return (
      <View style={styles.container}>
        <ActivityIndicator size="large" color="#4a90d9" />
        <Text style={styles.title}>Finding SkyTwin...</Text>
        <Text style={styles.subtitle}>
          Searching for SkyTwin on your local network.
        </Text>
      </View>
    );
  }

  // Found phase
  if (state.phase === 'found') {
    return (
      <View style={styles.container}>
        <View style={styles.successIcon}>
          <Text style={styles.successIconText}>OK</Text>
        </View>
        <Text style={styles.title}>Found SkyTwin on your network</Text>
        <Text style={styles.subtitle}>{state.baseUrl}</Text>
        <TouchableOpacity
          style={styles.primaryButton}
          onPress={handleConnect}
          disabled={connecting}
        >
          {connecting ? (
            <ActivityIndicator color="#fff" />
          ) : (
            <Text style={styles.primaryButtonText}>Connect</Text>
          )}
        </TouchableOpacity>
        <TouchableOpacity style={styles.secondaryButton} onPress={handleRetry}>
          <Text style={styles.secondaryButtonText}>Scan a different code</Text>
        </TouchableOpacity>
      </View>
    );
  }

  // Error phase
  if (state.phase === 'error') {
    // The 'no-mdns' cause is the office-WiFi case — make "Enter address
    // manually" the PRIMARY action there, since retrying mDNS won't help.
    const manualIsPrimary = state.cause === 'no-mdns' || state.cause === 'mdns-but-no-connect';
    return (
      <View style={styles.container}>
        <View style={styles.errorIcon}>
          <Text style={styles.errorIconText}>!</Text>
        </View>
        <Text style={styles.title}>SkyTwin not found on your network</Text>
        <Text style={styles.subtitle}>{state.message}</Text>
        {manualIsPrimary ? (
          <>
            <TouchableOpacity
              style={styles.primaryButton}
              onPress={() => setState({ phase: 'manual' })}
            >
              <Text style={styles.primaryButtonText}>Enter address manually</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.secondaryButton} onPress={handleRetry}>
              <Text style={styles.secondaryButtonText}>Try scanning again</Text>
            </TouchableOpacity>
          </>
        ) : (
          <>
            <TouchableOpacity style={styles.primaryButton} onPress={handleRetry}>
              <Text style={styles.primaryButtonText}>Try Again</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={styles.secondaryButton}
              onPress={() => setState({ phase: 'manual' })}
            >
              <Text style={styles.secondaryButtonText}>Enter address manually</Text>
            </TouchableOpacity>
          </>
        )}
      </View>
    );
  }

  // Manual entry phase
  return (
    <KeyboardAvoidingView
      style={styles.container}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
    >
      <Text style={styles.title}>Manual Connection</Text>
      <Text style={styles.subtitle}>
        Enter your computer's IP address. You can find it in SkyTwin desktop Settings.
      </Text>
      <TextInput
        style={styles.textInput}
        placeholder="e.g. 192.168.1.42 or 192.168.1.42:3100"
        placeholderTextColor="#888"
        value={manualIp}
        onChangeText={setManualIp}
        autoCapitalize="none"
        autoCorrect={false}
        keyboardType="url"
        returnKeyType="go"
        onSubmitEditing={handleManualConnect}
      />
      <TouchableOpacity
        style={styles.primaryButton}
        onPress={handleManualConnect}
        disabled={connecting}
      >
        {connecting ? (
          <ActivityIndicator color="#fff" />
        ) : (
          <Text style={styles.primaryButtonText}>Connect</Text>
        )}
      </TouchableOpacity>
      <TouchableOpacity style={styles.secondaryButton} onPress={handleRetry}>
        <Text style={styles.secondaryButtonText}>Back to QR scan</Text>
      </TouchableOpacity>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a2e',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
    marginTop: 16,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 15,
    color: '#a0a0b8',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 22,
    paddingHorizontal: 16,
  },
  cameraContainer: {
    width: 280,
    height: 280,
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 24,
  },
  camera: {
    flex: 1,
  },
  scanOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanFrame: {
    width: 200,
    height: 200,
    borderWidth: 2,
    borderColor: '#4a90d9',
    borderRadius: 12,
    backgroundColor: 'transparent',
  },
  primaryButton: {
    backgroundColor: '#4a90d9',
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 10,
    minWidth: 200,
    alignItems: 'center',
    marginBottom: 12,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  secondaryButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  secondaryButtonText: {
    color: '#4a90d9',
    fontSize: 14,
  },
  textInput: {
    backgroundColor: '#2a2a40',
    color: '#ffffff',
    borderRadius: 10,
    padding: 14,
    fontSize: 16,
    width: '100%',
    maxWidth: 340,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#3a3a54',
  },
  successIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#2ecc71',
    alignItems: 'center',
    justifyContent: 'center',
  },
  successIconText: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '700',
  },
  errorIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#e74c3c',
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorIconText: {
    color: '#ffffff',
    fontSize: 32,
    fontWeight: '700',
  },
});
