import React, { useState, useCallback, useRef, useEffect } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  ActivityIndicator,
  Alert,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { discoverSkyTwin, buildBaseUrl } from '../services/discovery';
import { SkyTwinApiClient } from '../services/api-client';
import { saveSession } from '../services/session-store';

interface PairingScreenProps {
  onPaired: () => void;
}

type PairingState =
  | { phase: 'scan' }
  | { phase: 'discovering'; token: string; userId: string; host: string | null }
  | { phase: 'found'; token: string; userId: string; baseUrl: string }
  | { phase: 'error'; message: string; token?: string; userId?: string }
  | { phase: 'manual' };

/**
 * QR code pairing screen.
 *
 * Scans a QR code generated by the desktop app, extracts the token and userId,
 * then discovers the SkyTwin API on the local network via mDNS.
 */
export function PairingScreen({ onPaired }: PairingScreenProps): React.JSX.Element {
  const [permission, requestPermission] = useCameraPermissions();
  const [state, setState] = useState<PairingState>({ phase: 'scan' });
  const [manualIp, setManualIp] = useState('');
  const [connecting, setConnecting] = useState(false);
  const scannedRef = useRef(false);

  // Reset scan lock when returning to scan phase
  useEffect(() => {
    if (state.phase === 'scan') {
      scannedRef.current = false;
    }
  }, [state.phase]);

  const parseQrUrl = useCallback(
    (url: string): { token: string; userId: string; host: string } | null => {
      try {
        const parsed = new URL(url);
        const token = parsed.searchParams.get('token');
        const userId = parsed.searchParams.get('userId');
        if (!token || !userId) return null;
        return { token, userId, host: parsed.host };
      } catch {
        return null;
      }
    },
    [],
  );

  const handleBarCodeScanned = useCallback(
    async (scanResult: { data: string }) => {
      // Prevent duplicate scans
      if (scannedRef.current) return;
      scannedRef.current = true;

      const parsed = parseQrUrl(scanResult.data);
      if (!parsed) {
        setState({
          phase: 'error',
          message: 'Invalid QR code. Make sure you scan the SkyTwin pairing code from your desktop.',
        });
        return;
      }

      setState({
        phase: 'discovering',
        token: parsed.token,
        userId: parsed.userId,
        host: parsed.host,
      });

      // Try mDNS discovery first
      const discovered = await discoverSkyTwin(5000, false);
      const baseUrl = discovered
        ? buildBaseUrl(discovered)
        : `http://${parsed.host}`;

      // Verify the API is reachable
      const client = new SkyTwinApiClient(baseUrl, parsed.token, 5000);
      const healthResult = await client.getServiceStatus();

      if (healthResult.success) {
        setState({
          phase: 'found',
          token: parsed.token,
          userId: parsed.userId,
          baseUrl,
        });
      } else {
        setState({
          phase: 'error',
          message: `SkyTwin not reachable at ${baseUrl}. Make sure your phone and computer are on the same network.`,
          token: parsed.token,
          userId: parsed.userId,
        });
      }
    },
    [parseQrUrl],
  );

  const handleConnect = useCallback(async () => {
    if (state.phase !== 'found') return;
    setConnecting(true);

    try {
      await saveSession(state.token, state.baseUrl, state.userId);
      onPaired();
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Failed to save session';
      Alert.alert('Connection Error', message);
    } finally {
      setConnecting(false);
    }
  }, [state, onPaired]);

  const handleManualConnect = useCallback(async () => {
    if (!manualIp.trim()) {
      Alert.alert('Enter an address', 'Please enter your computer\'s IP address or hostname.');
      return;
    }

    // Accept bare IP, IP:port, or full URL
    let baseUrl: string;
    const trimmed = manualIp.trim();
    if (trimmed.startsWith('http://') || trimmed.startsWith('https://')) {
      baseUrl = trimmed.replace(/\/+$/, '');
    } else if (trimmed.includes(':')) {
      baseUrl = `http://${trimmed}`;
    } else {
      baseUrl = `http://${trimmed}:3100`;
    }

    setConnecting(true);
    setState({
      phase: 'discovering',
      token: '',
      userId: '',
      host: null,
    });

    const client = new SkyTwinApiClient(baseUrl, '', 5000);
    const healthResult = await client.getServiceStatus();

    if (healthResult.success) {
      // Manual connection requires creating a session via the API.
      // For now, prompt the user to use QR pairing instead.
      Alert.alert(
        'SkyTwin Found',
        `Found SkyTwin at ${baseUrl}. To complete pairing, scan the QR code from your desktop app.`,
      );
      setState({ phase: 'scan' });
    } else {
      setState({
        phase: 'error',
        message: `Could not reach SkyTwin at ${baseUrl}. Check the address and make sure SkyTwin is running.`,
      });
    }

    setConnecting(false);
  }, [manualIp]);

  const handleRetry = useCallback(() => {
    setState({ phase: 'scan' });
  }, []);

  // Camera permission not yet determined
  if (!permission) {
    return (
      <View style={styles.container}>
        <ActivityIndicator size="large" color="#4a90d9" />
      </View>
    );
  }

  // Camera permission denied
  if (!permission.granted) {
    return (
      <View style={styles.container}>
        <Text style={styles.title}>Camera Access Needed</Text>
        <Text style={styles.subtitle}>
          SkyTwin needs camera access to scan the pairing QR code from your desktop.
        </Text>
        <TouchableOpacity style={styles.primaryButton} onPress={requestPermission}>
          <Text style={styles.primaryButtonText}>Grant Camera Access</Text>
        </TouchableOpacity>
      </View>
    );
  }

  // Scanning phase
  if (state.phase === 'scan') {
    return (
      <View style={styles.container}>
        <Text style={styles.title}>Pair with Desktop</Text>
        <Text style={styles.subtitle}>
          Open SkyTwin on your computer and scan the QR code shown in Settings.
        </Text>
        <View style={styles.cameraContainer}>
          <CameraView
            style={styles.camera}
            facing="back"
            barcodeScannerSettings={{
              barcodeTypes: ['qr'],
            }}
            onBarcodeScanned={handleBarCodeScanned}
          />
          <View style={styles.scanOverlay}>
            <View style={styles.scanFrame} />
          </View>
        </View>
        <TouchableOpacity
          style={styles.secondaryButton}
          onPress={() => setState({ phase: 'manual' })}
        >
          <Text style={styles.secondaryButtonText}>Enter address manually</Text>
        </TouchableOpacity>
      </View>
    );
  }

  // Discovering phase
  if (state.phase === 'discovering') {
    return (
      <View style={styles.container}>
        <ActivityIndicator size="large" color="#4a90d9" />
        <Text style={styles.title}>Finding SkyTwin...</Text>
        <Text style={styles.subtitle}>
          Searching for SkyTwin on your local network.
        </Text>
      </View>
    );
  }

  // Found phase
  if (state.phase === 'found') {
    return (
      <View style={styles.container}>
        <View style={styles.successIcon}>
          <Text style={styles.successIconText}>OK</Text>
        </View>
        <Text style={styles.title}>Found SkyTwin on your network</Text>
        <Text style={styles.subtitle}>{state.baseUrl}</Text>
        <TouchableOpacity
          style={styles.primaryButton}
          onPress={handleConnect}
          disabled={connecting}
        >
          {connecting ? (
            <ActivityIndicator color="#fff" />
          ) : (
            <Text style={styles.primaryButtonText}>Connect</Text>
          )}
        </TouchableOpacity>
        <TouchableOpacity style={styles.secondaryButton} onPress={handleRetry}>
          <Text style={styles.secondaryButtonText}>Scan a different code</Text>
        </TouchableOpacity>
      </View>
    );
  }

  // Error phase
  if (state.phase === 'error') {
    return (
      <View style={styles.container}>
        <View style={styles.errorIcon}>
          <Text style={styles.errorIconText}>!</Text>
        </View>
        <Text style={styles.title}>SkyTwin not found on your network</Text>
        <Text style={styles.subtitle}>{state.message}</Text>
        <TouchableOpacity style={styles.primaryButton} onPress={handleRetry}>
          <Text style={styles.primaryButtonText}>Try Again</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.secondaryButton}
          onPress={() => setState({ phase: 'manual' })}
        >
          <Text style={styles.secondaryButtonText}>Enter address manually</Text>
        </TouchableOpacity>
      </View>
    );
  }

  // Manual entry phase
  return (
    <KeyboardAvoidingView
      style={styles.container}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
    >
      <Text style={styles.title}>Manual Connection</Text>
      <Text style={styles.subtitle}>
        Enter your computer's IP address. You can find it in SkyTwin desktop Settings.
      </Text>
      <TextInput
        style={styles.textInput}
        placeholder="e.g. 192.168.1.42 or 192.168.1.42:3100"
        placeholderTextColor="#888"
        value={manualIp}
        onChangeText={setManualIp}
        autoCapitalize="none"
        autoCorrect={false}
        keyboardType="url"
        returnKeyType="go"
        onSubmitEditing={handleManualConnect}
      />
      <TouchableOpacity
        style={styles.primaryButton}
        onPress={handleManualConnect}
        disabled={connecting}
      >
        {connecting ? (
          <ActivityIndicator color="#fff" />
        ) : (
          <Text style={styles.primaryButtonText}>Check Connection</Text>
        )}
      </TouchableOpacity>
      <TouchableOpacity style={styles.secondaryButton} onPress={handleRetry}>
        <Text style={styles.secondaryButtonText}>Back to QR scan</Text>
      </TouchableOpacity>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a2e',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
    marginTop: 16,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 15,
    color: '#a0a0b8',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 22,
    paddingHorizontal: 16,
  },
  cameraContainer: {
    width: 280,
    height: 280,
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 24,
  },
  camera: {
    flex: 1,
  },
  scanOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanFrame: {
    width: 200,
    height: 200,
    borderWidth: 2,
    borderColor: '#4a90d9',
    borderRadius: 12,
    backgroundColor: 'transparent',
  },
  primaryButton: {
    backgroundColor: '#4a90d9',
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 10,
    minWidth: 200,
    alignItems: 'center',
    marginBottom: 12,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  secondaryButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  secondaryButtonText: {
    color: '#4a90d9',
    fontSize: 14,
  },
  textInput: {
    backgroundColor: '#2a2a40',
    color: '#ffffff',
    borderRadius: 10,
    padding: 14,
    fontSize: 16,
    width: '100%',
    maxWidth: 340,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#3a3a54',
  },
  successIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#2ecc71',
    alignItems: 'center',
    justifyContent: 'center',
  },
  successIconText: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '700',
  },
  errorIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#e74c3c',
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorIconText: {
    color: '#ffffff',
    fontSize: 32,
    fontWeight: '700',
  },
});
