import { query } from '../connection.js';

export type LifebookImportance = 'core' | 'secondary' | 'emerging';

/**
 * Shape of the `metadata` JSONB column. Optional fields keep the
 * representation small — an empty `{}` is the common case.
 */
export interface LifebookMetadata {
  /**
   * #321 user-set importance override. When set + still within its
   * freshness window, wins over the LLM's `importance` pick during
   * extraction-worker upserts.
   *
   * Freshness: `setAt + decayDays` defines the deadline.
   *   - `decayDays > 0` → expires after that many days; the worker
   *     resumes computing importance automatically after.
   *   - `decayDays === 0` → the "never auto-decay" sentinel; the
   *     override sticks until `clearImportanceOverride` is called.
   * To remove an override, call `clearImportanceOverride` regardless
   * of decayDays — setting `decayDays: 0` does NOT clear it (that
   * makes it permanent, not removed).
   */
  importanceOverride?: {
    value: LifebookImportance;
    setAt: string; // ISO 8601 — generated by the DB (now() at write time)
    decayDays: number; // 0 = never auto-decay
  };
}

export interface LifebookRow {
  id: string;
  user_id: string;
  domain_name: string;
  importance: LifebookImportance;
  sample_signals: string[];
  suggested_capabilities: string[];
  wing_id: string | null;
  detected_at: Date;
  last_seen_at: Date;
  hidden_at: Date | null;
  metadata: LifebookMetadata;
}

export interface UpsertLifebookInput {
  userId: string;
  domainName: string;
  importance: LifebookImportance;
  sampleSignals: string[];
  suggestedCapabilities: string[];
  wingId: string | null;
}

/**
 * Repository for `lifebooks` (#193 Child 1).
 *
 * The domain-extractor worker upserts one row per detected life domain
 * per user. Hidden rows survive — re-running extraction must not bring
 * them back. Only user-initiated `unhide` clears `hidden_at`.
 */
export const lifebookRepository = {
  /**
   * Upsert a lifebook by (user_id, domain_name).
   *
   * #321: when a row already exists with a fresh `importanceOverride`
   * in `metadata`, the worker-provided `importance` is IGNORED — the
   * user's override wins. Freshness check: `setAt` within `decayDays`
   * (treats `decayDays = 0` as "never auto-decay"). The CASE expression
   * happens in SQL so this stays race-free against concurrent
   * extraction runs.
   *
   * The override is NOT a write-blocker — `sample_signals`,
   * `suggested_capabilities`, `wing_id`, `last_seen_at` always update
   * fresh. Only `importance` itself is gated.
   */
  async upsert(input: UpsertLifebookInput): Promise<LifebookRow> {
    const result = await query<LifebookRow>(
      `INSERT INTO lifebooks
         (user_id, domain_name, importance, sample_signals, suggested_capabilities, wing_id, last_seen_at)
       VALUES ($1, $2, $3, $4::jsonb, $5::jsonb, $6, now())
       ON CONFLICT (user_id, domain_name) DO UPDATE SET
         importance = CASE
           WHEN lifebooks.metadata ? 'importanceOverride'
            AND (
              (lifebooks.metadata->'importanceOverride'->>'decayDays')::int = 0
              OR (lifebooks.metadata->'importanceOverride'->>'setAt')::timestamptz
                 > now() - ((lifebooks.metadata->'importanceOverride'->>'decayDays')::int || ' days')::interval
            )
           THEN (lifebooks.metadata->'importanceOverride'->>'value')::string
           ELSE EXCLUDED.importance
         END,
         sample_signals = EXCLUDED.sample_signals,
         suggested_capabilities = EXCLUDED.suggested_capabilities,
         wing_id = COALESCE(EXCLUDED.wing_id, lifebooks.wing_id),
         last_seen_at = EXCLUDED.last_seen_at
       RETURNING *`,
      [
        input.userId,
        input.domainName,
        input.importance,
        JSON.stringify(input.sampleSignals),
        JSON.stringify(input.suggestedCapabilities),
        input.wingId,
      ],
    );
    const row = result.rows[0];
    if (!row) throw new Error('lifebook upsert returned no row');
    return row;
  },

  /**
   * List visible lifebooks (hidden_at IS NULL) for a user, ordered
   * core → secondary → emerging, then most-recently-seen first.
   */
  async listVisible(userId: string): Promise<LifebookRow[]> {
    const result = await query<LifebookRow>(
      `SELECT * FROM lifebooks
       WHERE user_id = $1 AND hidden_at IS NULL
       ORDER BY
         CASE importance WHEN 'core' THEN 0 WHEN 'secondary' THEN 1 ELSE 2 END,
         last_seen_at DESC`,
      [userId],
    );
    return result.rows;
  },

  /**
   * List all lifebooks (including hidden) for a user. Used by the
   * Settings → Lifebooks management UX so the user can unhide.
   */
  async listAll(userId: string): Promise<LifebookRow[]> {
    const result = await query<LifebookRow>(
      `SELECT * FROM lifebooks
       WHERE user_id = $1
       ORDER BY last_seen_at DESC`,
      [userId],
    );
    return result.rows;
  },

  async findByDomain(userId: string, domainName: string): Promise<LifebookRow | null> {
    const result = await query<LifebookRow>(
      `SELECT * FROM lifebooks
       WHERE user_id = $1 AND domain_name = $2
       LIMIT 1`,
      [userId, domainName],
    );
    return result.rows[0] ?? null;
  },

  /**
   * Hide a lifebook from dashboards. The row is preserved so the wing
   * and its memories remain — only the surface visibility changes.
   */
  async hide(userId: string, domainName: string): Promise<boolean> {
    const result = await query(
      `UPDATE lifebooks
       SET hidden_at = now()
       WHERE user_id = $1 AND domain_name = $2 AND hidden_at IS NULL`,
      [userId, domainName],
    );
    return (result.rowCount ?? 0) > 0;
  },

  /**
   * Unhide a previously hidden lifebook. Idempotent.
   */
  async unhide(userId: string, domainName: string): Promise<boolean> {
    const result = await query(
      `UPDATE lifebooks
       SET hidden_at = NULL
       WHERE user_id = $1 AND domain_name = $2 AND hidden_at IS NOT NULL`,
      [userId, domainName],
    );
    return (result.rowCount ?? 0) > 0;
  },

  /**
   * #321: set a user importance override for a Lifebook. The value
   * lands on `metadata.importanceOverride` AND the `importance`
   * column is set to the same value immediately (so the next read
   * reflects the override without waiting for the extractor to
   * re-run). The `setAt` timestamp + `decayDays` window is what
   * `upsert` checks to decide whether to respect the override on
   * extraction.
   *
   * `setAt` is generated in SQL via `now()` so it matches the same
   * clock that `upsert`'s freshness CASE compares against. Going
   * through `new Date().toISOString()` on the app server would
   * introduce clock-skew between the API node and the CockroachDB
   * cluster — an override could be reported as expired when it's
   * still fresh, or vice versa. (Copilot caught the prior version.)
   *
   * `decayDays` 0 means "never auto-decay" — the override sticks
   * until explicit clear. Sensible default: 90.
   *
   * Returns the updated row or null if the (user, domain) doesn't
   * exist (caller can 404).
   */
  async setImportanceOverride(
    userId: string,
    domainName: string,
    value: LifebookImportance,
    decayDays = 90,
  ): Promise<LifebookRow | null> {
    const result = await query<LifebookRow>(
      `UPDATE lifebooks
       SET importance = $3,
           metadata = jsonb_set(
             metadata,
             '{importanceOverride}',
             jsonb_build_object(
               'value', $3::string,
               'setAt', now()::string,
               'decayDays', $4::int
             ),
             true
           )
       WHERE user_id = $1 AND domain_name = $2
       RETURNING *`,
      [userId, domainName, value, decayDays],
    );
    return result.rows[0] ?? null;
  },

  /**
   * #321: clear an existing override. The `importance` column stays at
   * its current value (caller can manually set it back if they want
   * the extractor to recompute on the next run; otherwise the next
   * extraction-worker upsert will set it).
   *
   * Idempotent — no-ops when the override doesn't exist.
   */
  async clearImportanceOverride(
    userId: string,
    domainName: string,
  ): Promise<LifebookRow | null> {
    const result = await query<LifebookRow>(
      `UPDATE lifebooks
       SET metadata = metadata - 'importanceOverride'
       WHERE user_id = $1 AND domain_name = $2
       RETURNING *`,
      [userId, domainName],
    );
    return result.rows[0] ?? null;
  },
};
