import { query } from '../connection.js';
import { mempalaceRepository } from './mempalace-repository.js';

export type LifebookImportance = 'core' | 'secondary' | 'emerging';

/**
 * Shape of the `metadata` JSONB column. Optional fields keep the
 * representation small — an empty `{}` is the common case.
 */
export interface LifebookMetadata {
  /**
   * #321 user-set importance override. When set + still within its
   * freshness window, wins over the LLM's `importance` pick during
   * extraction-worker upserts.
   *
   * Freshness: `setAt + decayDays` defines the deadline.
   *   - `decayDays > 0` → expires after that many days; the worker
   *     resumes computing importance automatically after.
   *   - `decayDays === 0` → the "never auto-decay" sentinel; the
   *     override sticks until `clearImportanceOverride` is called.
   * To remove an override, call `clearImportanceOverride` regardless
   * of decayDays — setting `decayDays: 0` does NOT clear it (that
   * makes it permanent, not removed).
   */
  importanceOverride?: {
    value: LifebookImportance;
    setAt: string; // ISO 8601 — generated by the DB (now() at write time)
    decayDays: number; // 0 = never auto-decay
  };

  /**
   * #193 AC#8 — set when the user added this domain manually
   * ("track 'Volunteering'") rather than the weekly extractor
   * detecting it. The extractor's `upsert` preserves this flag
   * (it never clears metadata it didn't write), so a manually-seeded
   * domain stays attributable even after the extractor starts
   * refreshing its signals/capabilities. UI uses it to label the
   * Lifebook "added by you" vs "auto-detected".
   */
  manuallyAdded?: boolean;
}

export interface LifebookRow {
  id: string;
  user_id: string;
  domain_name: string;
  importance: LifebookImportance;
  sample_signals: string[];
  suggested_capabilities: string[];
  wing_id: string | null;
  detected_at: Date;
  last_seen_at: Date;
  hidden_at: Date | null;
  metadata: LifebookMetadata;
}

export interface UpsertLifebookInput {
  userId: string;
  domainName: string;
  importance: LifebookImportance;
  sampleSignals: string[];
  suggestedCapabilities: string[];
  wingId: string | null;
}

export interface AddManualLifebookInput {
  userId: string;
  /** Trimmed display name; also the wing name. Must be non-empty. */
  domainName: string;
  /**
   * Optional starting importance. A user-seeded domain has no signal
   * history yet, so it defaults to `'emerging'` — the extractor can
   * promote it on the next run once memory accumulates.
   */
  importance?: LifebookImportance;
}

/**
 * Result of `addManual`. Typed result object (per CLAUDE.md) so the
 * route can distinguish "created", "already exists / re-surfaced", and
 * "invalid input" without try/catch on expected branches.
 */
export type AddManualLifebookResult =
  | { success: true; created: boolean; lifebook: LifebookRow }
  | { success: false; error: 'invalid_domain_name' };

/**
 * Repository for `lifebooks` (#193 Child 1).
 *
 * The domain-extractor worker upserts one row per detected life domain
 * per user. Hidden rows survive — re-running extraction must not bring
 * them back. Only user-initiated `unhide` clears `hidden_at`.
 */
export const lifebookRepository = {
  /**
   * Upsert a lifebook by (user_id, domain_name).
   *
   * #321: when a row already exists with a fresh `importanceOverride`
   * in `metadata`, the worker-provided `importance` is IGNORED — the
   * user's override wins. Freshness check: `setAt` within `decayDays`
   * (treats `decayDays = 0` as "never auto-decay"). The CASE expression
   * happens in SQL so this stays race-free against concurrent
   * extraction runs.
   *
   * The override is NOT a write-blocker — `sample_signals`,
   * `suggested_capabilities`, `wing_id`, `last_seen_at` always update
   * fresh. Only `importance` itself is gated.
   */
  async upsert(input: UpsertLifebookInput): Promise<LifebookRow> {
    const result = await query<LifebookRow>(
      `INSERT INTO lifebooks
         (user_id, domain_name, importance, sample_signals, suggested_capabilities, wing_id, last_seen_at)
       VALUES ($1, $2, $3, $4::jsonb, $5::jsonb, $6, now())
       ON CONFLICT (user_id, domain_name) DO UPDATE SET
         importance = CASE
           WHEN lifebooks.metadata ? 'importanceOverride'
            AND (
              (lifebooks.metadata->'importanceOverride'->>'decayDays')::int = 0
              OR (lifebooks.metadata->'importanceOverride'->>'setAt')::timestamptz
                 > now() - ((lifebooks.metadata->'importanceOverride'->>'decayDays')::int || ' days')::interval
            )
           THEN (lifebooks.metadata->'importanceOverride'->>'value')::string
           ELSE EXCLUDED.importance
         END,
         sample_signals = EXCLUDED.sample_signals,
         suggested_capabilities = EXCLUDED.suggested_capabilities,
         wing_id = COALESCE(EXCLUDED.wing_id, lifebooks.wing_id),
         last_seen_at = EXCLUDED.last_seen_at
       RETURNING *`,
      [
        input.userId,
        input.domainName,
        input.importance,
        JSON.stringify(input.sampleSignals),
        JSON.stringify(input.suggestedCapabilities),
        input.wingId,
      ],
    );
    const row = result.rows[0];
    if (!row) throw new Error('lifebook upsert returned no row');
    return row;
  },

  /**
   * #193 AC#8 — user adds a domain manually ("track 'Volunteering'").
   * Unlike the extractor's `upsert`, this is a deliberate user action,
   * so it:
   *
   *   1. Creates the MemPalace wing IMMEDIATELY (the AC's wording —
   *      "creates the wing immediately and informs the next extraction
   *      run"). `createWing` is idempotent on (user_id, name), so an
   *      existing wing is reused rather than duplicated.
   *   2. Inserts the lifebook row stamped `metadata.manuallyAdded = true`
   *      and starting at `emerging` importance (no signal history yet).
   *   3. On conflict (the domain already exists) RE-SURFACES it: clears
   *      `hidden_at` and bumps `last_seen_at`. This is the one path that
   *      is ALLOWED to unhide — a manual add is the user explicitly
   *      asking to track the domain again. The extractor's `upsert`
   *      deliberately does NOT clear `hidden_at`; that asymmetry is the
   *      point (hidden domains stay hidden across automatic re-detection,
   *      but the user can always opt back in).
   *
   * `importance` is set ONLY on insert. If the row already exists we do
   * not overwrite the extractor's (or the user's override) importance —
   * re-adding a domain shouldn't demote a `core` Lifebook back to
   * `emerging`. `metadata.manuallyAdded` is OR-merged so the flag sticks
   * even if the row predates this feature.
   *
   * The next extraction run sees the wing + row already present and
   * upserts against them normally — that's how the manual add "informs"
   * the extractor.
   *
   * Returns a typed result. `created` distinguishes a brand-new row from
   * a re-surfaced existing one so the API can report the right thing.
   */
  async addManual(input: AddManualLifebookInput): Promise<AddManualLifebookResult> {
    const domainName = input.domainName.trim();
    if (domainName.length === 0) {
      return { success: false, error: 'invalid_domain_name' };
    }
    const importance: LifebookImportance = input.importance ?? 'emerging';

    // 1. Create the wing immediately (idempotent on (user_id, name)).
    const wing = await mempalaceRepository.createWing({
      userId: input.userId,
      name: domainName,
      description: `Memories related to ${domainName}`,
      domains: [domainName],
    });

    // Pre-check existence so we can report `created` accurately. The
    // `xmax = 0` "did this INSERT fire" idiom is a PostgreSQL trick that
    // does NOT work on CockroachDB (xmax is always 0), so we mirror the
    // established `decisionRepository.create` / `approvalRepository.create`
    // pattern of a guard SELECT. The ON CONFLICT below still makes the
    // write itself atomic + idempotent under concurrent manual adds.
    const existing = await query<{ id: string }>(
      'SELECT id FROM lifebooks WHERE user_id = $1 AND domain_name = $2 LIMIT 1',
      [input.userId, domainName],
    );
    const created = existing.rows.length === 0;

    // 2/3. Insert-or-resurface the lifebook row.
    const result = await query<LifebookRow>(
      `INSERT INTO lifebooks
         (user_id, domain_name, importance, sample_signals, suggested_capabilities, wing_id, last_seen_at, metadata)
       VALUES ($1, $2, $3, '[]'::jsonb, '[]'::jsonb, $4, now(), '{"manuallyAdded": true}'::jsonb)
       ON CONFLICT (user_id, domain_name) DO UPDATE SET
         wing_id = COALESCE(lifebooks.wing_id, EXCLUDED.wing_id),
         hidden_at = NULL,
         last_seen_at = now(),
         metadata = lifebooks.metadata || '{"manuallyAdded": true}'::jsonb
       RETURNING *`,
      [input.userId, domainName, importance, wing.id],
    );
    const row = result.rows[0];
    if (!row) throw new Error('lifebook addManual returned no row');
    return { success: true, created, lifebook: row };
  },

  /**
   * List visible lifebooks (hidden_at IS NULL) for a user, ordered
   * core → secondary → emerging, then most-recently-seen first.
   */
  async listVisible(userId: string): Promise<LifebookRow[]> {
    const result = await query<LifebookRow>(
      `SELECT * FROM lifebooks
       WHERE user_id = $1 AND hidden_at IS NULL
       ORDER BY
         CASE importance WHEN 'core' THEN 0 WHEN 'secondary' THEN 1 ELSE 2 END,
         last_seen_at DESC`,
      [userId],
    );
    return result.rows;
  },

  /**
   * List all lifebooks (including hidden) for a user. Used by the
   * Settings → Lifebooks management UX so the user can unhide.
   */
  async listAll(userId: string): Promise<LifebookRow[]> {
    const result = await query<LifebookRow>(
      `SELECT * FROM lifebooks
       WHERE user_id = $1
       ORDER BY last_seen_at DESC`,
      [userId],
    );
    return result.rows;
  },

  async findByDomain(userId: string, domainName: string): Promise<LifebookRow | null> {
    const result = await query<LifebookRow>(
      `SELECT * FROM lifebooks
       WHERE user_id = $1 AND domain_name = $2
       LIMIT 1`,
      [userId, domainName],
    );
    return result.rows[0] ?? null;
  },

  /**
   * Hide a lifebook from dashboards. The row is preserved so the wing
   * and its memories remain — only the surface visibility changes.
   */
  async hide(userId: string, domainName: string): Promise<boolean> {
    const result = await query(
      `UPDATE lifebooks
       SET hidden_at = now()
       WHERE user_id = $1 AND domain_name = $2 AND hidden_at IS NULL`,
      [userId, domainName],
    );
    return (result.rowCount ?? 0) > 0;
  },

  /**
   * Unhide a previously hidden lifebook. Idempotent.
   */
  async unhide(userId: string, domainName: string): Promise<boolean> {
    const result = await query(
      `UPDATE lifebooks
       SET hidden_at = NULL
       WHERE user_id = $1 AND domain_name = $2 AND hidden_at IS NOT NULL`,
      [userId, domainName],
    );
    return (result.rowCount ?? 0) > 0;
  },

  /**
   * #321: set a user importance override for a Lifebook. The value
   * lands on `metadata.importanceOverride` AND the `importance`
   * column is set to the same value immediately (so the next read
   * reflects the override without waiting for the extractor to
   * re-run). The `setAt` timestamp + `decayDays` window is what
   * `upsert` checks to decide whether to respect the override on
   * extraction.
   *
   * `setAt` is generated in SQL via `now()` so it matches the same
   * clock that `upsert`'s freshness CASE compares against. Going
   * through `new Date().toISOString()` on the app server would
   * introduce clock-skew between the API node and the CockroachDB
   * cluster — an override could be reported as expired when it's
   * still fresh, or vice versa. (Copilot caught the prior version.)
   *
   * `decayDays` 0 means "never auto-decay" — the override sticks
   * until explicit clear. Sensible default: 90.
   *
   * Returns the updated row or null if the (user, domain) doesn't
   * exist (caller can 404).
   */
  async setImportanceOverride(
    userId: string,
    domainName: string,
    value: LifebookImportance,
    decayDays = 90,
  ): Promise<LifebookRow | null> {
    const result = await query<LifebookRow>(
      `UPDATE lifebooks
       SET importance = $3,
           metadata = jsonb_set(
             metadata,
             '{importanceOverride}',
             jsonb_build_object(
               'value', $3::string,
               'setAt', now()::string,
               'decayDays', $4::int
             ),
             true
           )
       WHERE user_id = $1 AND domain_name = $2
       RETURNING *`,
      [userId, domainName, value, decayDays],
    );
    return result.rows[0] ?? null;
  },

  /**
   * #319: inline fact-edit. Replace the extracted `sample_signals[index]`
   * fact with a user-supplied correction. Used by the per-Lifebook detail
   * page's inline edit affordance — the user spotted a wrong extracted
   * fact (a Health appointment date, a misread recruiter name) and fixed
   * it in place.
   *
   * The write is index-targeted and bounds-checked IN SQL so it stays
   * race-free against a concurrent extractor upsert that may have just
   * reordered/replaced the array: `jsonb_set` only touches the targeted
   * element, and the `jsonb_array_length` guard in the WHERE clause means
   * an out-of-range index updates nothing (the caller distinguishes
   * "lifebook missing" from "index out of range" via `findByDomain`).
   *
   * Returns the updated row, or null when the (user, domain) doesn't
   * exist OR the index is out of range for the current array. The
   * route layer is responsible for writing the provenance correction
   * node — this method only mutates the fact text.
   */
  async editSampleSignal(
    userId: string,
    domainName: string,
    index: number,
    correctedText: string,
  ): Promise<LifebookRow | null> {
    const result = await query<LifebookRow>(
      `UPDATE lifebooks
       SET sample_signals = jsonb_set(
             sample_signals,
             ARRAY[$3::int::string],
             to_jsonb($4::string),
             false
           )
       WHERE user_id = $1
         AND domain_name = $2
         AND $3::int >= 0
         AND $3::int < jsonb_array_length(sample_signals)
       RETURNING *`,
      [userId, domainName, index, correctedText],
    );
    return result.rows[0] ?? null;
  },

  /**
   * #321: clear an existing override. The `importance` column stays at
   * its current value (caller can manually set it back if they want
   * the extractor to recompute on the next run; otherwise the next
   * extraction-worker upsert will set it).
   *
   * Idempotent — no-ops when the override doesn't exist.
   */
  async clearImportanceOverride(
    userId: string,
    domainName: string,
  ): Promise<LifebookRow | null> {
    const result = await query<LifebookRow>(
      `UPDATE lifebooks
       SET metadata = metadata - 'importanceOverride'
       WHERE user_id = $1 AND domain_name = $2
       RETURNING *`,
      [userId, domainName],
    );
    return result.rows[0] ?? null;
  },
};
