/**
 * key-derivation.ts — scrypt-based passphrase key derivation.
 *
 * CRYPTO CHOICE NOTE (substitution from issue spec):
 * The issue spec (#183 AC#5) called for Argon2id. Node.js has no built-in
 * Argon2id implementation; adding the `argon2` npm package requires native
 * compilation which is a deployment hazard in this monorepo. We use Node's
 * built-in `crypto.scrypt` instead.
 *
 * scrypt is memory-hard (like Argon2id) and production-proven. Parameters:
 *   N = 2^15 = 32 768 (CPU/memory cost)
 *   r = 8            (block size)
 *   p = 1            (parallelism)
 *   keylen = 32      (AES-256 key length in bytes)
 *
 * This choice is documented in the package README.
 */

import { scrypt, randomBytes, createHash, timingSafeEqual } from 'node:crypto';

/** Key derivation parameters — kept as named constants for auditability. */
const SCRYPT_N = 32768; // 2^15
const SCRYPT_R = 8;
const SCRYPT_P = 1;
const KEY_LEN = 32; // bytes — AES-256

/**
 * OpenSSL's default scrypt memory ceiling is 32MB (exactly 128 * N * r when
 * N=32768, r=8). The default check is >=, so N=32768,r=8 is rejected unless we
 * explicitly raise maxmem. We allow 64MB so the production default N fits with
 * headroom for future r increases.
 */
const SCRYPT_MAX_MEM = 64 * 1024 * 1024; // 64 MB

/** Length of per-user salts generated by this module. */
export const SALT_LENGTH = 32; // bytes

/**
 * Derive a 32-byte AES key from a passphrase and a per-user salt using
 * scrypt. The returned Buffer is suitable for use with AES-256-GCM.
 *
 * NEVER persist the returned Buffer. It must live only in memory (KeyCache).
 */
export function deriveKey(passphrase: string, salt: Buffer): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    scrypt(
      passphrase,
      salt,
      KEY_LEN,
      { N: SCRYPT_N, r: SCRYPT_R, p: SCRYPT_P, maxmem: SCRYPT_MAX_MEM },
      (err, derivedKey) => {
        if (err) {
          reject(err);
        } else {
          resolve(derivedKey);
        }
      },
    );
  });
}

/**
 * Generate a random per-user salt. Call once at vault initialisation;
 * store in user_credential_vault_meta.passphrase_salt.
 */
export function generateSalt(): Buffer {
  return randomBytes(SALT_LENGTH);
}

/**
 * Compute a SHA-256 hash of a derived key for passphrase verification.
 * This hash is stored in user_credential_vault_meta.passphrase_hash.
 *
 * IMPORTANT: this is a hash of the *derived key*, not the passphrase itself.
 * It lets us verify the user supplied the correct passphrase without
 * storing the passphrase or the key.
 */
export function hashDerivedKey(key: Buffer): Buffer {
  return createHash('sha256').update(key).digest();
}

/**
 * Verify that a candidate passphrase produces the same derived key as the
 * stored hash. Uses timingSafeEqual to prevent timing attacks.
 *
 * Returns true if the passphrase matches, false otherwise.
 */
export async function verifyPassphrase(
  candidatePassphrase: string,
  salt: Buffer,
  storedHash: Buffer,
): Promise<boolean> {
  const candidateKey = await deriveKey(candidatePassphrase, salt);
  const candidateHash = hashDerivedKey(candidateKey);

  if (candidateHash.length !== storedHash.length) return false;
  return timingSafeEqual(candidateHash, storedHash);
}

/**
 * Minimum acceptable passphrase length (characters). Enforced at the API
 * layer; exported here as the canonical constant.
 */
export const MIN_PASSPHRASE_LENGTH = 12;
