import type {
  MemoryPort,
  MemoryCapability,
  RawSignal,
  SearchSemanticOptions,
  KnowledgeEntity,
  KnowledgeTriple,
  Episode,
  SemanticHit,
  GraphWalkSpec,
  KnowledgeNode,
  TimeRange,
  EpisodeFilter,
  MemoryEntityType,
  EntityFilter,
  SummarizeSpec,
  MemorySummary,
  CompressedView,
  MemoryRecord,
} from '@skytwin/memory-port';
import { createLogger } from '@skytwin/core';
import {
  HashEmbeddingProvider,
  type EmbeddingProvider,
  InMemoryBrainStore,
  rrfFold,
  buildTierWeightFn,
  type BrainPageRow,
  type RrfHit,
  type TierCalibration,
} from '@skytwin/memory-gbrain-crdb-adapter';

const log = createLogger('memory-gbrain-embedded');

/**
 * Backend the EmbeddedGbrainMemoryPort talks to. Either:
 *   - 'crdb'   — the CRDB-backed `repository.ts` (production default).
 *   - 'memory' — the `InMemoryBrainStore` (unit tests / hermetic boots).
 */
export type EmbeddedGbrainBackend = 'crdb' | 'memory';

export interface EmbeddedGbrainOptions {
  /** Identifier of the user this port operates on. Required because every
   *  brain table is user-scoped — the MemoryPort interface deliberately
   *  doesn't carry userId on every call, so callers fix it at construction.
   */
  userId: string;
  /** Embedding provider. Defaults to deterministic hash trick. */
  embedding?: EmbeddingProvider;
  /** Choose 'crdb' (default) or 'memory'. */
  backend?: EmbeddedGbrainBackend;
  /** Pre-built in-memory store (only used when backend = 'memory'). */
  store?: InMemoryBrainStore;
  /** RRF constant. Default 60. */
  rrfK?: number;
  /** Vector candidate pool size. Default = max(k*4, 40). */
  candidatePoolSize?: number;
  /**
   * Whether searchSemantic blocks on synchronous embedding. Default true.
   *
   * When false, searchSemantic falls back to text-only RRF (the vector side
   * contributes empty), which is faster but loses recall. Useful when an
   * external embedding provider is misbehaving and we want graceful
   * degradation rather than a slow failure.
   */
  embedQueriesSynchronously?: boolean;
}

/**
 * EmbeddedGbrainMemoryPort — the real, in-process gbrain backend.
 *
 * Implements `MemoryPort` against the `brain_*` CockroachDB tables (or an
 * in-memory store for tests). Provides:
 *
 *   - Hybrid retrieval (vector cosine + tsvector FTS folded via RRF).
 *   - Typed entities + temporal triples + episodes + raw signals.
 *   - Lazy embedding pipeline: writes return immediately, embeddings are
 *     generated by the worker draining the brain_embedding_jobs queue.
 *
 * Capability set:
 *   semantic_search, code_aware_search, temporal_triples, episodic, graph_walk
 *
 * Notably absent: spatial_wings (mempalace-only) and aaak_compression
 * (mempalace-only). The hybrid composer routes those to the secondary
 * (mempalace) backend.
 *
 * Why this exists: PR #215 shipped a CLI shell-out skeleton that returns []
 * unless `gbrain` is on the host PATH. This embedded variant runs against the
 * SkyTwin DB stack natively — no separate process, no separate Postgres, no
 * extra install step. It's what we ship as the default per-user backend.
 */
export class EmbeddedGbrainMemoryPort implements MemoryPort {
  private readonly userId: string;
  private readonly embedding: EmbeddingProvider;
  private readonly backend: EmbeddedGbrainBackend;
  private readonly store: InMemoryBrainStore | undefined;
  private readonly rrfK: number;
  /** User override; when undefined we compute `max(k*4, 40)` per query. */
  private readonly candidatePoolOverride: number | undefined;
  private readonly embedQueriesSync: boolean;

  // Lazy-loaded CRDB repository (only imported when backend === 'crdb').
  private crdbRepo: typeof import('@skytwin/memory-gbrain-crdb-adapter') | null = null;

  constructor(opts: EmbeddedGbrainOptions) {
    if (!opts.userId) {
      throw new Error('EmbeddedGbrainMemoryPort: userId is required');
    }
    this.userId = opts.userId;
    this.embedding = opts.embedding ?? new HashEmbeddingProvider();
    this.backend = opts.backend ?? 'crdb';
    this.store = opts.store ?? (this.backend === 'memory' ? new InMemoryBrainStore() : undefined);
    this.rrfK = opts.rrfK ?? 60;
    this.candidatePoolOverride = opts.candidatePoolSize;
    this.embedQueriesSync = opts.embedQueriesSynchronously ?? true;
  }

  capabilities(): Set<MemoryCapability> {
    return new Set<MemoryCapability>([
      'semantic_search',
      'code_aware_search',
      'temporal_triples',
      'episodic',
      'graph_walk',
    ]);
  }

  // ── Lazy CRDB import ─────────────────────────────────────────────────────

  private async crdb(): Promise<typeof import('@skytwin/memory-gbrain-crdb-adapter')> {
    if (this.crdbRepo) return this.crdbRepo;
    const mod = await import('@skytwin/memory-gbrain-crdb-adapter');
    this.crdbRepo = mod;
    return mod;
  }

  // ── Write ─────────────────────────────────────────────────────────────────

  async recordSignal(s: RawSignal): Promise<void> {
    const data = s.data ?? {};
    const summaryText = this.summariseSignal(s);
    // #251 Layer 1: connectors stamp `data.authoringTier` (whether the user
    // wrote the content or merely received it). Project it onto the brain
    // page metadata so Layer 2 retrieval weighting can read it without a
    // join back to the signal row. No-op when the connector didn't stamp it
    // (e.g. calendar signals, custom event ingests).
    //
    // Also stamp `bodyLen` so brief-reply downweighting can fire: an
    // `authored_*` page whose body is shorter than BRIEF_BODY_THRESHOLD
    // gets treated as `inbox_personal` weight in the RRF fold. The length
    // here is the indexed summary content, not the raw email body, which
    // is the right size to measure against (one-line replies summarize to
    // tens of chars; multi-paragraph emails to hundreds).
    const pageMetadata = this.buildPageMetadata(s, data, summaryText);
    if (this.backend === 'memory') {
      this.store!.insertSignal({
        id: s.id,
        userId: this.userId,
        source: s.source,
        type: s.type,
        data,
        signalTimestamp: s.timestamp,
      });
      // Match the CRDB path's conditional embedding wiring (only set
      // `embeddingModel` when an embedding actually succeeded). Prior
      // implementation set `embeddingModel` even on failure, which left
      // pages with a non-null model but null embedding — diverging from
      // the CRDB row shape and breaking dim-based replay logic.
      const embedding = await this.embedding.embed(summaryText).catch(() => undefined);
      this.store!.insertPage({
        userId: this.userId,
        title: `${s.source}/${s.type}`,
        content: summaryText,
        source: 'signal',
        sourceRef: s.id,
        metadata: pageMetadata,
        ...(embedding ? { embedding, embeddingModel: this.embedding.model } : {}),
      });
      return;
    }
    const repo = await this.crdb();
    await repo.insertSignal({
      id: s.id,
      userId: this.userId,
      source: s.source,
      type: s.type,
      data,
      signalTimestamp: s.timestamp,
    });
    let embedding: number[] | undefined;
    try {
      embedding = await this.embedding.embed(summaryText);
    } catch (err) {
      log.warn('embedding failed at write time; will be retried by worker', {
        reason: err instanceof Error ? err.name : 'unknown',
      });
    }
    await repo.insertPage({
      userId: this.userId,
      title: `${s.source}/${s.type}`,
      content: summaryText,
      source: 'signal',
      sourceRef: s.id,
      metadata: pageMetadata,
      ...(embedding ? { embedding, embeddingModel: this.embedding.model } : {}),
    });
  }

  /**
   * Build the `brain_pages.metadata` object for a signal-derived page.
   * Always carries `signalSource` / `signalType` and `bodyLen` (length of
   * the summarised content, for Layer 2's brief-reply downweight). Carries
   * `authoringTier` and `fromAddress` only when the connector supplied
   * them — `fromAddress` is the From header (or equivalent) extracted from
   * `data`, used by the per-sender bulk hide action so a user can "stop
   * indexing this sender" without having to delete pages one by one.
   *
   * Kept tolerant of unknown shapes — defensive against future connectors
   * that may pass an object or null where we expect a string.
   */
  private buildPageMetadata(
    s: RawSignal,
    data: Record<string, unknown>,
    content: string,
  ): Record<string, unknown> {
    const metadata: Record<string, unknown> = {
      signalSource: s.source,
      signalType: s.type,
      bodyLen: content.length,
    };
    const tier = data['authoringTier'];
    if (typeof tier === 'string' && tier.length > 0) {
      metadata['authoringTier'] = tier;
    }
    // Normalize fromAddress at write time so the bulk-hide query is a
    // simple equality match against `metadata->>'fromAddress'`. We lower
    // the address to avoid case-sensitivity bugs at query time. The same
    // shape lives in `@skytwin/connectors` as `extractBareAddress`; inlined
    // here as a 3-line helper to avoid pulling the connectors package
    // into the memory layer's dependency graph.
    const rawFrom = data['from'];
    if (typeof rawFrom === 'string' && rawFrom.trim().length > 0) {
      const angle = rawFrom.match(/<([^>]+)>/);
      const bare = angle?.[1]
        ? angle[1].trim().toLowerCase()
        : rawFrom.trim().toLowerCase();
      if (bare.length > 0) metadata['fromAddress'] = bare;
    }
    return metadata;
  }

  async recordEntity(e: KnowledgeEntity): Promise<void> {
    if (this.backend === 'memory') {
      this.store!.upsertEntity({
        id: e.id,
        userId: this.userId,
        name: e.name,
        entityType: e.entityType,
        attributes: e.attributes ?? {},
        firstSeenAt: e.firstSeenAt,
        lastSeenAt: e.lastSeenAt,
      });
      // Match CRDB path: only set embeddingModel when embedding succeeded.
      const embedding = await this.embedding.embed(`${e.name} ${e.entityType}`).catch(() => undefined);
      this.store!.insertPage({
        userId: this.userId,
        title: e.name,
        content: `${e.name} (${e.entityType})`,
        source: 'extract',
        sourceRef: e.id,
        metadata: { entityType: e.entityType, attributes: e.attributes ?? {} },
        ...(embedding ? { embedding, embeddingModel: this.embedding.model } : {}),
      });
      return;
    }
    const repo = await this.crdb();
    await repo.upsertEntity({
      id: e.id,
      userId: this.userId,
      name: e.name,
      entityType: e.entityType,
      attributes: e.attributes ?? {},
      firstSeenAt: e.firstSeenAt,
      lastSeenAt: e.lastSeenAt,
    });
    let embedding: number[] | undefined;
    try {
      embedding = await this.embedding.embed(`${e.name} ${e.entityType}`);
    } catch {
      // ignore — async backfill will retry
    }
    await repo.insertPage({
      userId: this.userId,
      title: e.name,
      content: `${e.name} (${e.entityType})`,
      source: 'extract',
      sourceRef: e.id,
      metadata: { entityType: e.entityType, attributes: e.attributes ?? {} },
      ...(embedding ? { embedding, embeddingModel: this.embedding.model } : {}),
    });
  }

  async recordTriple(t: KnowledgeTriple): Promise<void> {
    if (this.backend === 'memory') {
      this.store!.insertTriple({
        id: t.id,
        userId: this.userId,
        subject: t.subject,
        predicate: t.predicate,
        object: t.object,
        validFrom: t.validFrom,
        validTo: t.validTo,
        evidence: (t.evidence as Record<string, unknown> | undefined) ?? {},
      });
      return;
    }
    const repo = await this.crdb();
    await repo.insertTriple({
      id: t.id,
      userId: this.userId,
      subject: t.subject,
      predicate: t.predicate,
      object: t.object,
      validFrom: t.validFrom,
      validTo: t.validTo,
      evidence: (t.evidence as Record<string, unknown> | undefined) ?? {},
    });
  }

  async recordEpisode(e: Episode): Promise<void> {
    if (this.backend === 'memory') {
      this.store!.insertEpisode({
        id: e.id,
        userId: this.userId,
        wing: e.wing,
        summary: e.summary,
        metadata: e.metadata ?? {},
        startedAt: e.startedAt,
        endedAt: e.endedAt,
      });
      // Also index for search. Match CRDB path: only set embeddingModel
      // when embedding succeeded.
      const embedding = await this.embedding.embed(e.summary).catch(() => undefined);
      this.store!.insertPage({
        userId: this.userId,
        title: e.wing ? `episode (${e.wing})` : 'episode',
        content: e.summary,
        source: 'episode',
        sourceRef: e.id,
        metadata: { wing: e.wing },
        ...(embedding ? { embedding, embeddingModel: this.embedding.model } : {}),
      });
      return;
    }
    const repo = await this.crdb();
    await repo.insertEpisode({
      id: e.id,
      userId: this.userId,
      wing: e.wing,
      summary: e.summary,
      metadata: e.metadata ?? {},
      startedAt: e.startedAt,
      endedAt: e.endedAt,
    });
    let embedding: number[] | undefined;
    try {
      embedding = await this.embedding.embed(e.summary);
    } catch {
      // ignore
    }
    await repo.insertPage({
      userId: this.userId,
      title: e.wing ? `episode (${e.wing})` : 'episode',
      content: e.summary,
      source: 'episode',
      sourceRef: e.id,
      metadata: { wing: e.wing },
      ...(embedding ? { embedding, embeddingModel: this.embedding.model } : {}),
    });
  }

  // ── Read ──────────────────────────────────────────────────────────────────

  async searchSemantic(
    query: string,
    k: number,
    options?: SearchSemanticOptions,
  ): Promise<SemanticHit[]> {
    if (!query.trim()) return [];
    let embedding: number[] | undefined;
    if (this.embedQueriesSync) {
      try {
        embedding = await this.embedding.embed(query);
      } catch (err) {
        log.warn('query embedding failed; falling back to text-only RRF', {
          reason: err instanceof Error ? err.name : 'unknown',
        });
      }
    }

    const hits = await this.searchInternal(query, k, embedding, options);
    return hits.map(rrfHitToSemanticHit);
  }

  /**
   * Code-aware search hook. v1.0.5 implementation: same as searchSemantic but
   * boosts page sources tagged 'code'. The boost is applied post-RRF; sources
   * with `source = 'code'` get a 1.25x multiplier on rrfScore. This is the
   * same shape upstream gbrain uses — full code-aware features (definition
   * lookup, AST-aware token boost) ship in a fast-follow.
   */
  async searchCodeAware(query: string, k: number): Promise<SemanticHit[]> {
    const hits = await this.searchSemantic(query, k);
    const reranked = hits.map((hit) => ({
      ...hit,
      score: hit.source === 'code' ? hit.score * 1.25 : hit.score,
    }));
    return reranked.sort((a, b) => b.score - a.score);
  }

  private async searchInternal(
    queryText: string,
    k: number,
    queryEmbedding?: number[],
    options?: SearchSemanticOptions,
  ): Promise<RrfHit[]> {
    // Per-query default per the docstring: max(k*4, 40). Previously the
    // constructor pinned a 40 floor that ignored k, so k=20 queries pulled
    // only 40 candidates from each side before RRF — truncating recall.
    const candidatePoolSize = this.candidatePoolOverride ?? Math.max(k * 4, 40);

    // #251 Layer 2: build a tier-weight function if the user has opted in.
    // Reading settings is best-effort — if it fails (no row yet, pre-043
    // schema, transient DB hiccup) we silently fall back to pure RRF.
    const tierWeight = await this.resolveTierWeightFn();

    // #300: surface the authoring-tier filter to both store + CRDB
    // backends. Empty list → omitted, treated as "no filter."
    const authoringTier =
      options?.authoringTier && options.authoringTier.length > 0
        ? options.authoringTier
        : undefined;

    if (this.backend === 'memory') {
      return this.store!.hybridSearch({
        userId: this.userId,
        query: queryText,
        ...(queryEmbedding ? { queryEmbedding } : {}),
        k,
        candidatePoolSize,
        rrfK: this.rrfK,
        ...(tierWeight ? { tierWeight } : {}),
        ...(authoringTier ? { authoringTier } : {}),
      });
    }
    const repo = await this.crdb();
    return repo.hybridSearch({
      userId: this.userId,
      query: queryText,
      ...(queryEmbedding ? { queryEmbedding } : {}),
      k,
      candidatePoolSize,
      rrfK: this.rrfK,
      ...(tierWeight ? { tierWeight } : {}),
      ...(authoringTier ? { authoringTier } : {}),
    });
  }

  /**
   * Look up the per-user `tier_weighting` toggle (and the calibration band)
   * and return a tier-weight function if both are present, else `undefined`.
   * Defensive: any failure leaves retrieval as pure RRF, the safe default.
   */
  private async resolveTierWeightFn(): Promise<
    ((metadata: unknown) => number) | undefined
  > {
    let enabled = false;
    let calibration: TierCalibration = 'normal';

    try {
      if (this.backend === 'memory') {
        const row = this.store!.getSettings(this.userId);
        if (row) {
          enabled = row.tier_weighting === true;
          calibration = row.tier_calibration ?? 'normal';
        }
      } else {
        const repo = await this.crdb();
        const row = await repo.getSettings(this.userId);
        if (row) {
          enabled = row.tier_weighting === true;
          calibration = row.tier_calibration ?? 'normal';
        }
      }
    } catch (err) {
      log.warn('tier-weight settings lookup failed; falling back to pure RRF', {
        reason: err instanceof Error ? err.name : 'unknown',
      });
      return undefined;
    }

    if (!enabled) return undefined;
    return buildTierWeightFn(calibration);
  }

  async walkGraph(spec: GraphWalkSpec): Promise<KnowledgeNode[]> {
    const visited = new Set<string>();
    const queue: Array<{ nodeId: string; depth: number }> = [
      { nodeId: spec.startNodeId, depth: 0 },
    ];
    const nodes: KnowledgeNode[] = [];

    while (queue.length > 0) {
      const item = queue.shift();
      if (!item) break;
      if (visited.has(item.nodeId) || item.depth > spec.maxDepth) continue;
      visited.add(item.nodeId);

      const triples = await this.fetchTriples({
        subject: item.nodeId,
        predicate: spec.edgeFilter?.predicate,
        limit: 50,
      });

      for (const t of triples) {
        nodes.push({ id: t.id, type: 'triple', data: this.tripleRowToType(t) });
        if (!visited.has(t.object) && item.depth < spec.maxDepth) {
          queue.push({ nodeId: t.object, depth: item.depth + 1 });
        }
      }
    }
    return nodes;
  }

  async getEpisodes(range: TimeRange, filter?: EpisodeFilter): Promise<Episode[]> {
    if (this.backend === 'memory') {
      const rows = this.store!.getEpisodes(this.userId, {
        from: range.from,
        to: range.to,
        wing: filter?.wing,
      });
      return rows
        .filter((row) => filterByMinDuration(row.started_at, row.ended_at, filter?.minDurationMs))
        .map((row) => ({
          id: row.id,
          userId: row.user_id,
          wing: row.wing ?? undefined,
          summary: row.summary,
          startedAt: row.started_at,
          endedAt: row.ended_at,
          metadata: row.metadata,
        }));
    }
    const repo = await this.crdb();
    const rows = await repo.getEpisodes(this.userId, {
      from: range.from,
      to: range.to,
      wing: filter?.wing,
    });
    return rows
      .filter((row) => filterByMinDuration(row.started_at, row.ended_at, filter?.minDurationMs))
      .map((row) => ({
        id: row.id,
        userId: row.user_id,
        wing: row.wing ?? undefined,
        summary: row.summary,
        startedAt: row.started_at,
        endedAt: row.ended_at,
        metadata: row.metadata,
      }));
  }

  async getEntitiesByType(
    type: MemoryEntityType,
    filter?: EntityFilter,
  ): Promise<KnowledgeEntity[]> {
    const rows = this.backend === 'memory'
      ? this.store!.getEntities(this.userId, { entityType: type, nameLike: filter?.name })
      : await (await this.crdb()).getEntities(this.userId, { entityType: type, nameLike: filter?.name });
    return rows.map((row) => ({
      id: row.id,
      userId: row.user_id,
      name: row.name,
      entityType: row.entity_type as MemoryEntityType,
      attributes: row.attributes,
      firstSeenAt: row.first_seen_at,
      lastSeenAt: row.last_seen_at,
    }));
  }

  async getTriples(
    subject?: string,
    predicate?: string,
    object?: string,
  ): Promise<KnowledgeTriple[]> {
    const rows = await this.fetchTriples({
      subject,
      predicate,
      object,
      limit: 500,
    });
    return rows.map((row) => this.tripleRowToType(row));
  }

  // ── Aggregations ──────────────────────────────────────────────────────────

  async summarize(spec: SummarizeSpec): Promise<MemorySummary> {
    const maxTokens = spec.maxTokens ?? 500;
    const charsPerToken = 4;
    const maxChars = maxTokens * charsPerToken;

    const triples = await this.fetchTriples({ limit: 200 });
    const lines: string[] = [];
    const citations: Array<{ ref: string; kind: string }> = [];
    for (const t of triples) {
      const line = `${t.subject} ${t.predicate} ${t.object}`;
      if ((lines.join('\n').length + line.length) > maxChars) break;
      lines.push(line);
      citations.push({ ref: t.id, kind: 'triple' });
    }
    const text = lines.join('\n') || `Summary for scope: ${spec.scope}`;
    return {
      text,
      tokenCount: Math.ceil(text.length / charsPerToken),
      citations,
    };
  }

  async compress(maxTokens: number): Promise<CompressedView> {
    const summary = await this.summarize({ scope: 'user-profile', maxTokens });
    const now = new Date();
    const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    return {
      entries: [
        {
          summary: summary.text,
          sourceCount: summary.citations.length,
          periodFrom: weekAgo,
          periodTo: now,
        },
      ],
      totalSourcesCompressed: summary.citations.length,
    };
  }

  // ── Migration ─────────────────────────────────────────────────────────────

  async *exportAll(): AsyncIterable<MemoryRecord> {
    const repo = this.backend === 'memory'
      ? null
      : await this.crdb();

    const signals = repo
      ? await repo.getAllSignals(this.userId)
      : this.store!.getAllSignals(this.userId);
    for (const s of signals) {
      yield {
        kind: 'signal',
        payload: {
          id: s.id,
          source: s.source,
          type: s.type,
          timestamp: s.signal_timestamp,
          data: s.data,
        },
      };
    }

    const entities = repo
      ? await repo.getEntities(this.userId, {})
      : this.store!.getEntities(this.userId, {});
    for (const e of entities) {
      yield {
        kind: 'entity',
        payload: {
          id: e.id,
          userId: e.user_id,
          name: e.name,
          entityType: e.entity_type as MemoryEntityType,
          attributes: e.attributes,
          firstSeenAt: e.first_seen_at,
          lastSeenAt: e.last_seen_at,
        },
      };
    }

    const triples = repo
      ? await repo.getTriples(this.userId, { limit: 10000 })
      : this.store!.getTriples(this.userId, { limit: 10000 });
    for (const t of triples) {
      yield {
        kind: 'triple',
        payload: this.tripleRowToType(t),
      };
    }

    const episodes = repo
      ? await repo.getEpisodes(this.userId, { limit: 10000 })
      : this.store!.getEpisodes(this.userId, { limit: 10000 });
    for (const e of episodes) {
      yield {
        kind: 'episode',
        payload: {
          id: e.id,
          userId: e.user_id,
          wing: e.wing ?? undefined,
          summary: e.summary,
          startedAt: e.started_at,
          endedAt: e.ended_at,
          metadata: e.metadata,
        },
      };
    }
  }

  async importAll(records: AsyncIterable<MemoryRecord>): Promise<{ imported: number; skipped: number }> {
    let imported = 0;
    let skipped = 0;
    for await (const record of records) {
      try {
        switch (record.kind) {
          case 'signal':
            await this.recordSignal(record.payload as RawSignal);
            break;
          case 'entity':
            await this.recordEntity(record.payload as KnowledgeEntity);
            break;
          case 'triple':
            await this.recordTriple(record.payload as KnowledgeTriple);
            break;
          case 'episode':
            await this.recordEpisode(record.payload as Episode);
            break;
        }
        imported++;
      } catch (err) {
        if (
          err instanceof Error &&
          (err.message.includes('duplicate') ||
            err.message.includes('already exists') ||
            err.message.includes('unique constraint') ||
            err.message.includes('conflict'))
        ) {
          skipped++;
        } else {
          throw err;
        }
      }
    }
    return { imported, skipped };
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  private async fetchTriples(filter: {
    subject?: string;
    predicate?: string;
    object?: string;
    limit?: number;
  }) {
    if (this.backend === 'memory') {
      return this.store!.getTriples(this.userId, filter);
    }
    const repo = await this.crdb();
    return repo.getTriples(this.userId, filter);
  }

  private tripleRowToType(row: {
    id: string;
    user_id: string;
    subject: string;
    predicate: string;
    object: string;
    valid_from: Date;
    valid_to: Date | null;
    evidence: Record<string, unknown>;
  }): KnowledgeTriple {
    const triple: KnowledgeTriple = {
      id: row.id,
      userId: row.user_id,
      subject: row.subject,
      predicate: row.predicate,
      object: row.object,
      validFrom: row.valid_from,
    };
    if (row.valid_to) triple.validTo = row.valid_to;
    if (row.evidence && Object.keys(row.evidence).length > 0) {
      const ev = row.evidence as { signalId?: string; sourceRef?: string };
      if (ev.signalId || ev.sourceRef) triple.evidence = ev;
    }
    return triple;
  }

  private summariseSignal(s: RawSignal): string {
    const data = s.data ?? {};
    const subj = typeof data['subject'] === 'string' ? (data['subject'] as string) : '';
    const from = typeof data['from'] === 'string' ? (data['from'] as string) : '';
    const text = typeof data['text'] === 'string' ? (data['text'] as string) : '';
    const summary = typeof data['summary'] === 'string' ? (data['summary'] as string) : '';
    const parts: string[] = [];
    if (subj) parts.push(subj);
    if (from) parts.push(`from: ${from}`);
    if (summary) parts.push(summary);
    if (!summary && text) parts.push(text.substring(0, 500));
    if (parts.length === 0) parts.push(`${s.source}/${s.type}`);
    return parts.join(' — ');
  }
}

function rrfHitToSemanticHit(hit: { id: string; rrfScore: number; page: BrainPageRow }): SemanticHit {
  const result: SemanticHit = {
    id: hit.page.source_ref ?? hit.id,
    score: hit.rrfScore,
    content: hit.page.content,
    source: hit.page.source,
  };
  if (hit.page.metadata && Object.keys(hit.page.metadata).length > 0) {
    result.metadata = hit.page.metadata;
  }
  return result;
}

function filterByMinDuration(
  startedAt: Date,
  endedAt: Date,
  minDurationMs: number | undefined,
): boolean {
  if (!minDurationMs) return true;
  return endedAt.getTime() - startedAt.getTime() >= minDurationMs;
}

// Re-export for the export-by-name version (kept as part of the public API).
export { rrfFold };
